### ISSUE TITLE
open code

### ISSUE THREAD

**Issue by 1006245347** [openpilot-hub/devpilot-intellij#104]
**Describe the bug**
关联界面的index.html内部代码都被混淆了

**To Reproduce**
webview文件夹下的index.html文件代码被混淆，修改会话界面非常困难

**Expected behavior**
把index.html正式源码公布

**Environment (please complete the following information):**
v2.6.0

**Additional context**
把index.html正式源码公布

**Comment by xiangtianyu** [comment]
See this repo https://github.com/openpilot-hub/devpilot-h5

**Comment by 1006245347** [comment]
Copy to clipboard , 有bug ，只能复制最后一次的结果数据，多次会话后选前面的结果内容右键复制到剪切板，数据只能是最后一次的结果

**Comment by xiangtianyu** [comment]
> Copy to clipboard , 有bug ，只能复制最后一次的结果数据，多次会话后选前面的结果内容右键复制到剪切板，数据只能是最后一次的结果

This is fixed in the latest version, it will upload to marketplace in few days

**Comment by 1006245347** [comment]
交互有缺陷，vscode版本的更好，一键置顶，列表滚动条，会话历史列表缓存，这都没。。。

**Comment by 1006245347** [comment]
bug , 再网页的 shift+enter可以换行，再intellij idea插件界面无法使用换行快捷键
