### ISSUE TITLE
Follow IDE system language

### ISSUE THREAD

**Issue by wapkch** [openpilot-hub/devpilot-intellij#15]
**Is your feature request related to a problem? Please describe.**
It would be nice if the plugin language could follows IntelliJ IDEA.

**Comment by xiangtianyu** [comment]
Actually, idea doesn't support multipule language default, if you want to setup different language, you should install language plugin. So we'd rather switch language in our devpilot settings.

**Comment by wapkch** [comment]
Quite reasonable. Thanks!
