### ISSUE TITLE
generate comments not meet expectation 

### ISSUE THREAD

**Issue by xiangtianyu** [openpilot-hub/devpilot-intellij#16]
**Describe the bug**
generate comments result always include unexpected info

**To Reproduce**
1. select a method and choose generate comments
2. It will probability return some comments include "java" and so on
<img width="1112" alt="image" src="https://github.com/openpilot-hub/devpilot-intellij/assets/10825900/dab72bd4-1974-4a89-85f8-f5208f95be22">

**Comment by PerryZhao** [comment]
Yes, you are right! We found that this problem does exist when using Azure GPT3.5 version 1103, let me fix it.
