### ISSUE TITLE
OpenAi Service supports setting model

### ISSUE THREAD

**Issue by myoss** [openpilot-hub/devpilot-intellij#17]
**The current setting does not support setting the model name**
<img width="524" alt="SCR-20231214-qazs-2" src="https://github.com/openpilot-hub/devpilot-intellij/assets/6986459/e190c819-b940-4fdc-ab21-26f8c0d08522">

**Describe the solution you'd like**
#### 1. Add model settings
<img width="576" alt="SCR-20231214-qbrx-2" src="https://github.com/openpilot-hub/devpilot-intellij/assets/6986459/e533df3b-1fb1-4a6c-806b-3a888401e934">

#### 2. model list
<img width="559" alt="image" src="https://github.com/openpilot-hub/devpilot-intellij/assets/6986459/a4d7dada-1ca2-4052-8278-2c67b4a06642">

#### 3. custom model
<img width="561" alt="image" src="https://github.com/openpilot-hub/devpilot-intellij/assets/6986459/659eeb9c-d87b-4083-beaa-2a0b26d5b51a">

**Comment by xiangtianyu** [comment]
Ok, we will support this soon~

**Comment by myoss** [comment]
```
gpt-3.5-turbo
gpt-4
gpt-4-32k
Custom Model
```
