### ISSUE TITLE
Request for Support of OpenAI Streaming Response Interface

### ISSUE THREAD

**Issue by myoss** [openpilot-hub/devpilot-intellij#20]
### Describe the Issue
I've noticed that currently when using the OpenAI API, it supports synchronous requests. However, for large text or scenarios where responses are needed progressively, I believe supporting a streaming response interface would be a very useful feature.

### Feature Request
I would like the OpenAI API to support a streaming response interface, allowing us to receive responses gradually for processing large text, rather than waiting for the entire text processing to complete before receiving a response. This would be particularly beneficial for handling large text data or real-time applications.

### Expected Outcome
I hope to be able to use the OpenAI streaming response interface like this:

```python
# Pseudo code example
response = openai.stream_request('text to process')
for chunk in response:
    process_chunk(chunk)

**Comment by xiangtianyu** [comment]
Good idea, we may support stream api in future
