### ISSUE TITLE
Is this project still being updated?

### ISSUE THREAD

**Issue by tjlcast** [openpilot-hub/devpilot-intellij#36]
Hello
I saw that the latest version of this plugin in the market is 2.3.0 from 2024, but it seems that the Main branch of this repository hasn’t been updated for a long time.
If it is still being updated, could you please tell me where I can find the updated branch?

Thanks a lot.

**Comment by xiangtianyu** [comment]
We are currently optimizing the user experience, this repo is still being updated. We will continuously open source our code in the future.

**Comment by tjlcast** [comment]
Thank you! We’re glad you’re looking forward to our work. It’s promising to be a convenient tool.
