### ISSUE TITLE
How to choose a model for private in plugin configuration

### ISSUE THREAD

**Issue by feisc** [openpilot-hub/devpilot-intellij#39]
environment：win10，Idea 2023.1.6，devpilot-1.2.0.zip（github）

I found that the configuration of readme contains an option to select a model, but when I installed it, I did not find this option. How should I handle this? thank you very much
![企业微信截图_17155889923302](https://github.com/openpilot-hub/devpilot-intellij/assets/22266880/56488ebe-bd0e-4de9-9950-78534aea3a18)
![企业微信截图_17155889454577](https://github.com/openpilot-hub/devpilot-intellij/assets/22266880/a59841f3-cf69-4698-9fb9-f1d1a28b2dcb)

@geeklog @xiangtianyu

**Comment by xiangtianyu** [comment]
This change is modified in the "main" and not deploy a version yet, so if you want to use this feature, you may build the plugin by yourself

**Comment by feisc** [comment]
thank you very much
