### ISSUE TITLE
Devpilot plugin's page constantly appears blank

### ISSUE THREAD

**Issue by whk06** [openpilot-hub/devpilot-intellij#43]
- OS version: Windows 10
- IDEA version: 2023.1.6
- Plugin version: Devpilot-2.4.2

Hi, I'm confused that the plugin, which was build by myself, is constantly appears blank.

I just set `DefaultConst.AUTH_ON`  and `DefaultConst.TELEMETRY_ON` to false.What should I do?

Thanks!
<img width="406" alt="1719992874534" src="https://github.com/openpilot-hub/devpilot-intellij/assets/66070416/e3095b87-f992-4a98-a885-2a69f5ed2b72">

@xiangtianyu

**Comment by xiangtianyu** [comment]
hello, @whk06 we've tried this version in different os, and we all success. If you want to find the problem, you may run in debug mode, and run the devpilot in "idea sandbox mode". Then you can debug and find for more info

**Comment by whk06** [comment]
Thank you very much. @xiangtianyu
