### ISSUE TITLE
Switching the language settings under WeChat user status will cause the code completion to be turned off

### ISSUE THREAD

**Issue by littleli0n** [openpilot-hub/devpilot-intellij#51]
**Describe the bug**
Switching the language settings under WeChat user status will cause the code completion to be turned off.

**To Reproduce**
1. Being in the status of a WeChat user and having the code completion feature enabled.
2. Switching the language settings on the settings page.

**Expected behavior**
Switching languages does not cause the code completion feature to be turned off.

**Environment (please complete the following information):**
 - OS: win10
 - IDEA Version 2022.2.2
 - Plugin Version  2.4.2

**Comment by xiangtianyu** [comment]
It's a bug, i'll fix it immediately
