### ISSUE TITLE
New features - Code Completion

### ISSUE THREAD

**Issue by corgy-w** [openpilot-hub/devpilot-intellij#6]
Highly recommended to utilize contextual code completion with features similar to Copilot, which can be triggered by pressing the TAB key.

**Comment by carminedigre** [comment]
any update on this future?

**Comment by xiangtianyu** [comment]
> any update on this feature?

We are working for it, it will publish in future

**Comment by yuyuyulin** [comment]
any update on this feature?

i see updated the plugins  in market

**Comment by corgy-w** [comment]
> any update on this feature?
> 
> i see updated the plugins in market

@yuyuyulin This feature is now officially supported.

**Comment by yuyuyulin** [comment]
> > any update on this feature?
> > i see updated the plugins in market
> 
> @yuyuyulin This feature is now officially supported.

Will this feature continue to be open source in the future? i see the github updated 4 months ago.

**Comment by xiangtianyu** [comment]
We update this feature in new version.
