### ISSUE TITLE
PyCharm cannot install the latest plugin

### ISSUE THREAD

**Issue by xiangtianyu** [openpilot-hub/devpilot-intellij#65]
<img width="370" alt="image" src="https://github.com/user-attachments/assets/3ba9ce5f-4391-4044-a5fa-2328037e9239">

When install latest plugin in pycharm and other ide like goland, it will report bug

**Comment by maozhen520** [comment]
[https://github.com/openpilot-hub/devpilot-intellij/pull/66](url)
