### ISSUE TITLE
NPE Risk: The non-existent ModelTypeEnum will cause the DevPilot settings page to fail to load properly.

### ISSUE THREAD

**Issue by PerryZhao** [openpilot-hub/devpilot-intellij#8]
If a ModelType is removed in the future, users using that ModelType will not be able to load the configuration page normally. ModelServiceEnum and SessionTypeEnum also have the same problem

https://github.com/openpilot-hub/devpilot-intellij/blob/5fb2f5c19ec22622c816e69de1519149e285266d/src/main/java/com/zhongan/devpilot/enums/ModelServiceEnum.java#L23-L33

**Comment by xiangtianyu** [comment]
You are right, would you like to fix this problem?
